version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:9090/-/ready || exit 1",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./shared/:/tmp/shared/
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor


  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    # rancher user port 8080 and 8081
    command: "--enable_load_reader=true --port=8082"
    # this needs to run on the host network or you get no task stats etc.  Known bug!
    network_mode: host
    restart: always
    healthcheck:
      test:
        #ENV CADVISOR_HEALTHCHECK_URL=http://localhost:8080/healthz
        #CMD wget --quiet --tries=1 --spider $CADVISOR_HEALTHCHECK_URL || exit 1
        #HEALTHCHECK --interval=30s --timeout=3s \
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:8082/healthz || exit 1",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    ports:
    - 8082:8082
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /dev/klog:/dev/klog:ro 
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis

  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli PING || exit 1",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    ports:
    - 6379:6379
